apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
  namespace: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx-web-server-app
  ports:
    - protocol: TCP
      port: 80
