apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-server
  namespace: nginx
  labels:
    app: nginx-web-server-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web-server-app
  template:
    metadata:
      labels:
        app: nginx-web-server-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
