apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: canary
  name: canary-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: canary
